services:

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    env_file: .env
    environment:
      WA_HOST_1: "host.docker.internal"
      WA_HOST_2: "host.docker.internal"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data:/app/data
      - ./lead_database:/app/lead_database
      - ./scraped_data:/app/scraped_data
      - ./logs:/app/logs
      - ./client_data:/app/client_data
      - ./chat_history:/app/chat_history
      - ./credentials.yaml:/app/credentials.yaml:ro
    restart: unless-stopped
